## Alacritty Themes:
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = [
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.925

[window.dimensions]
columns = 185
lines = 60

[window.padding]
x = 15
y = 15

[window.position]
x = 125
y = 125
